### PR TITLE
Implement end poll

### PR DESCRIPTION
**Pull request by kaakaa**
## What does this PR do?
* Create ID of poll by [rs/xid](https://github.com/rs/xid)
* Add `End Poll` button to any posts of poll
* When pushing `End Poll` button, update the post to fixed message (don't count votes)

### CODE REVIEW

**Comment by Hanzei** [comment]
@kaakaa Just a short note: I didn't forget this PR, but I first want finish our discussion about the data store.

**Comment by Hanzei** [comment]
I tried to test this PR but activating the plugin failed. 
```
fork/exec /plugin/plugin: no such file or directory
[2018/01/24 21:24:50 CET] [EROR] unable to start plugin: matterpoll: timed out waiting for plugin
```
Did you test this PR yourself? Did it work?

**Comment by kaakaa** [comment]
Yes, I tested this PR in my local and it works fine.

`fork/exec /plugin/plugin: no such file or directory` says that Mattermost cannot find the executable file.

For testing, when I change executable file path in `plugin.yaml` to `plu` and upload plugin to Mattermost, the following log is output.

> [2018/01/25 10:46:51 JST] [EROR] unable to start plugin: matterpoll: fork/exec plugins/matterpoll/plu: no such file or directory

In my machine, Mattermost search executable file in `/plugins/${plugin_id}/${executable_path}`.
But your Mattermost is searching file in `plugin/plugin`. It looks strange.

What version of mattermost-server did you use?

**Comment by Hanzei** [comment]
I'm using a local dev environment which runs with the latest master. There seems to be a bug on master. Switching to 4.6 release solved the problem.

**Pull request closed without merging**
