### PR TITLE
Update Spanish translation for 1.4.0

### PR DESCRIPTION
**Pull request by ernestoittig**

### CODE REVIEW

**Comment by ernestoittig** [comment]
Something to note.
When I generated the JSON files to translate using `goi18n`, I noticed that the translation of `response.vote.multi.updated` had the same text for the "one" and "other" categories. This may lead the translator to think that they should be the same.
```json
{
  "response.vote.multi.updated": {
    "hash": "sha1-213785e569b994863b96b984772e9497f8629bbc",
    "one": "Your vote has been counted. You have {{.Remains}} votes left.",
    "other": "Your vote has been counted. You have {{.Remains}} votes left."
  }
}
```
I checked the [English](https://github.com/matterpoll/matterpoll/blob/63b8c76a283544b314cc2f3f9a2fb2f7c41c6da4/assets/i18n/active.en.json#L59) and [German](https://github.com/matterpoll/matterpoll/blob/63b8c76a283544b314cc2f3f9a2fb2f7c41c6da4/assets/i18n/active.de.json#L211) translations to see if this was correct and saw that, in both files, the "one" and "other" categories were different, so I updated my translation accordingly.
```json
{
  "response.vote.multi.updated": {
    "hash": "sha1-213785e569b994863b96b984772e9497f8629bbc",
    "one": "Su voto ha sido contado. Le queda {{.Remains}} voto.",
    "other": "Su voto ha sido contado. Le quedan {{.Remains}} votos."
  }
}
```
(_votos_ is the plural of _voto_)
If this is correct, the [French translation](https://github.com/matterpoll/matterpoll/blob/63b8c76a283544b314cc2f3f9a2fb2f7c41c6da4/assets/i18n/active.fr.json#L213) may have been affected by this confusion, as I see _votes_ being used for both categories, but I might be wrong since I don't know much French.

**Comment by hanzei** [comment]
@ernestoittig Your translation is correct. If it's applicable, the language should use `other` and `one`. But there are some languages where it's the same.

**Comment by hanzei** [comment]
@ldidry Can you confirm that the French translation is correct?

**Review by hanzei — APPROVED** [review]

**Comment by ldidry** [comment]
Indeed, I have been confused. I’ll correct this in a few minutes.

**Pull request merged**
