### PR TITLE
Set button color

### LINKED ISSUE #267: Customize button color
#### Summary
Changing buttons colors depending on their role (Answer, Add Options, Delete/End...) improves visibility. 

Example:
* Answer Option - blue
* Add Option - grey
* Delete/End - red

#### Additional context
webapp: [\[MM\-22734\] Support different interactive message button styles by kosgrz · Pull Request \#4993 · mattermost/mattermost\-webapp](https://github.com/mattermost/mattermost-webapp/pull/4993)
mobile: [MM\-10160 \- support interactive button styles by RyanCommits · Pull Request \#3896 · mattermost/mattermost\-mobile](https://github.com/mattermost/mattermost-mobile/pull/3896)

### PR DESCRIPTION
**Pull request by kaakaa**
fixes #267 

## Summary

The details is discussed in #267.

## TODO

- [x] fix webapp tests

### CODE REVIEW

**Comment by kaakaa** [comment]
## Notes

This PR will not break styles of existing poll with ExperimentalUI, but once users update their vote, style will be changed.

https://user-images.githubusercontent.com/1453749/117113418-68012480-adc5-11eb-878c-3260475e5266.mov

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Comment by hanzei** [comment]
My only feedback is that the answer fields look a bit scant. What do you think about the feedback at https://github.com/matterpoll/matterpoll/issues/267#issuecomment-692675536

> For the yes and no functionality. wondering if we should just follow the emoji reaction pattern, where it is grayed out if you have not selected it, and blue outlined when you have.


Surely, that would only be for the experimental UI.

**Comment by kaakaa** [comment]
Thanks @hanzei!

I tried to implemented the reaction pattern, but decided that it was not suitable because the colors conflicted with other buttons. I pasted the sample on the last of [my comment].(https://github.com/matterpoll/matterpoll/issues/267#issuecomment-787932617).
> Just one thing, following the emoji reaction pattern seems to be confusion, so I used inverted color pattern for yes / no functionality.
image

**Review by hanzei — APPROVED** [review]

**Pull request merged**
