### PR TITLE
Add config option for trigger

### LINKED ISSUE #16: Add config option for trigger

### PR DESCRIPTION
**Pull request by Hanzei**
Todo:
- [x] Add tests
- [x] Fix tests

Fixes #16

### CODE REVIEW

**Comment by Hanzei** [comment]
@kaakaa I tried to add tests for this, but failed. Do you have experience with [testify/mock](https://godoc.org/github.com/stretchr/testify/mock) and could help me out? Of course if you have time.

**Comment by Hanzei** [comment]
♥️ thank you!

**Comment by kaakaa** [comment]
👍 

I can work on adding tests. Would you like me to do that?

**Comment by Hanzei** [comment]
Thank you, but I'm currently working on this

**Comment by Hanzei** [comment]
This is now ready for review

**Comment by kaakaa** [comment]
Uh...Sorry, I removed `Do not merge` label.
Can I merge this?

**Comment by Hanzei** [comment]
I would like to cut a bugfix release with v0.0.3 and the merge this as a new feature for v0.1.0

**Pull request merged**
