### PR TITLE
Fix release file name for deploy

### PR DESCRIPTION
**Pull request by kaakaa**

### CODE REVIEW

**Comment by hanzei** [comment]
@kaakaa Mind if we release v1.0.1 with this? This way we can text it again and if people really want a CI build release, they can use v1.0.1.

**Comment by hanzei** [comment]
Mind if I delete https://github.com/matterpoll/matterpoll/releases/tag/deploy-test?

**Comment by kaakaa** [comment]
Yes, we should release new patch version (v1.0.1). because we better leave your uploaded binary.

**Comment by hanzei** [comment]
See https://github.com/matterpoll/matterpoll/pull/98

**Pull request merged**
