### PR TITLE
Release 1.0.0

### LINKED ISSUE #78: Future planing
Development on Matterpoll is quite rapid at the moment. But I think its time to decide which changes we want to make before declaring this plugins stable and release Matterpoll 1.0. I propose to ditch v0.2 and release v1.0 as the next major release. Given that there a some fixes for plugins coming in Mattermost 5.4 I would plan to release Matterpoll 1.0 at the same time as 5.4 comes out.

#59 and #62 should go into v1.0, if we accept this ideas as good. If https://github.com/mattermost/mattermost-server/pull/9429 makes it into Mattermost 5.4 we could also use this.

@kaakaa Are you fine with releasing Matterpoll 1.0 soon? Are the more changes you want to make before this?

### PR DESCRIPTION
**Pull request by hanzei**
Requires
- #85 
- #93 

Fixes #78

### CODE REVIEW

**Comment by hanzei** [comment]
Woops, good catch. Fixed this.

**Comment by lkraav** [comment]
@hanzei is there supposed to be a `com.github.matterpoll.matterpoll.tar.gz` package to download, like there is for 0.1.0? README.md is vague on what exactly should be downloaded from Releases page, is the basic github source tarball also OK, or not.

**Comment by geberl** [comment]
> README.md is vague on what exactly should be downloaded from Releases page

Putting the downloaded source into Mattermost's plugin dir does not work. The plugin needs to be compiled, there is a makefile included.

@hanzei / @kaakaa Is a binary coming?

**Comment by hanzei** [comment]
Wow, you guys are fast!

For some reason Travis did't deploy the binary to GitHub. Because of this I had to build it locally and upload it. Please download `com.github.matterpoll.matterpoll-1.0.0.tar.gz` on https://github.com/matterpoll/matterpoll/releases/tag/v1.0.0 and check if everything works a expected.

**Comment by geberl** [comment]
I had to manually `chmod +x /mattermost/plugins/com.github.matterpoll.matterpoll/server/dist/plugin-linux-amd64` to get the plugin starting up. Maybe add this to the description.

Now I got the plugin responding correctly to `curl -v https://mattermost.mydomain.com/plugins/com.github.matterpoll.matterpoll/` with a HTTP 200 code and `Thanks for using Matterpoll v1.0.0`. But it's responding with a 404 to `curl -v https://mattermost.mydomain.com/plugins/com.github.matterpoll.matterpoll/logo_dark.png`. Might be related to https://github.com/matterpoll/matterpoll/issues/91

**Comment by JtheBAB** [comment]
I just downloaded the release package that @hanzei mention. Extract it and it works out of the box.

**Comment by kaakaa** [comment]
Thanks @geberl and @JtheBAB.

We supposed that users upload plugin from system console of Mattermost.  In this way, you might not need to extract binary from .tar.gz and add permission. 
Just upload `com.github.matterpoll.matterpoll-1.0.0.tar.gz` published from [releases page](https://github.com/matterpoll/matterpoll/releases/tag/v1.0.0) and it will be available.

https://github.com/matterpoll/matterpoll#installation
> 2. Upload this file in the Mattermost System Console > Plugins > Management page to install the plugin. To learn more about how to upload a plugin, see the documentation.

Do you have any reason why you don't upload plugin from system console?

---

I'll take deep look for the problem about `logo_dark.png`. Thank you for reporting it.

**Comment by geberl** [comment]
@kaakaa Thanks, I can confirm that the `chmod +x ...` step I mentioned above is not needed if the plugin tar.gz is uploaded via Mattermost's web interface.

The `logo_dark.png` thing is unaffected by that btw.

**Comment by hanzei** [comment]
We fixed the build problem and released v1.0.1. Check out https://github.com/matterpoll/matterpoll/releases/tag/v1.0.1, if you want a CI build package.

**Comment by kaakaa** [comment]
@geberl Thank you for letting me know it.

If you confirm that `logo_dark.png` is missing from browser, it may be because of the cache.
After uploading `.tar.gz` from console, could you confirm it by `curl -v https://mattermost.mydomain.com/plugins/com.github.matterpoll.matterpoll/logo_dark.png`?

**Comment by hanzei** [comment]
Mind continuing the discussion on the missing icon in https://github.com/matterpoll/matterpoll/issues/91?

**Pull request merged**
