### PR TITLE
Add FR translation

### PR DESCRIPTION
**Pull request by ldidry**

### CODE REVIEW

**Comment by hanzei** [comment]
Thanks for the PR @ldidry!

Would your also be open maintaining the France translation in the future?

**Comment by ldidry** [comment]
Sure.

**Comment by ldidry** [comment]
Could you mention me when there will be new strings to translate?

**Comment by hanzei** [comment]
Sure. I'm not sure how the process will be (see https://github.com/matterpoll/matterpoll/issues/138). What you think about:

- When a new (major) version will releases soon, I will open an issue informing about this.
- I will ping all translators to inform them about this.
- They open PR's with new translations, which (may) get reviewed by other translators.
- After all translation PR's are merged, the new version is released.

**Comment by ldidry** [comment]
Perfect :ok_hand:

**Pull request merged**
