### PR TITLE
1.2.0 Docs

### PR DESCRIPTION
**Pull request by hanzei**
Only https://github.com/matterpoll/matterpoll/pull/175 needs a doc update. Hope I didn't missed something else.

### CODE REVIEW

**Comment by kaakaa** [comment]
If we merge #160 in time, it should be written in [Settings section](https://github.com/matterpoll/matterpoll#settings).

**Comment by hanzei** [comment]
@kaakaa Do you want to write to documentation or should I?

**Comment by kaakaa** [comment]
@hanzei okay, I'll create an another PR for docs about #160 later.

**Comment by hanzei** [comment]
@kaakaa Would you mind just pushing it into this branch? Then we can merge them together?

**Comment by kaakaa** [comment]
Sure 👍  I pushed it.

**Pull request merged**
